/**
 * lib/interactionEngine.ts
 *
 * Server-only. Imports herb/formula/interaction JSON data.
 * Called exclusively via /api/interactions — never imported in client components.
 *
 * NOTE: This tool assumes standard clinical dosages. Interaction severity may vary
 * based on dosage and herb-to-drug ratio. For professional reference only.
 */

import { lookupInteraction as lookupInteractionFromService } from "@/lib/clinicalDataService";
import { FEATURE_FLAGS } from "@/lib/featureFlags";
import formulaData from "@/data/formulaMap.json";
import formulaDataExpanded from "@/data/formulaMapExpanded.json";
import herbLibraryData from "@/data/herbLibrary.json";
import herbLibraryEnrichedData from "@/data/herbLibraryEnriched.json";

import type {
  SeverityLevel,
  EvidenceLevel,
  HerbIdentity,
  DrugIdentity,
  Citation,
  DataSource,
  InteractionMatch,
  FormulaIdentity,
  FormulaHerbDetail,
  InteractionEngineResult,
  WesternMed,
  TCMInput,
  CheckInteractionsOptions,
  DataFreshness,
} from "@/lib/types/clinical";

export type {
  SeverityLevel,
  EvidenceLevel,
  HerbIdentity,
  DrugIdentity,
  Citation,
  DataSource,
  InteractionMatch,
  FormulaIdentity,
  FormulaHerbDetail,
  InteractionEngineResult,
  WesternMed,
  TCMInput,
  CheckInteractionsOptions,
  DataFreshness,
} from "@/lib/types/clinical";

export {
  SEVERITY_LABELS,
  SEVERITY_STYLES,
  SEVERITY_ICONS,
} from "@/lib/severityUtils";

// ---------------------------------------------------------------------------
// Optional enriched datasets (generated by scripts/ingestTcmBank.ts)
// ---------------------------------------------------------------------------

type EnrichedHerbEntry = {
  id: string;
  pinyin: string;
  latin: string;
  english: string;
  nccaom_code: string | null;
  trustTier: "silver";
  source: "tcmbank_research";
  tcmbank_id?: string;
  active_constituent?: string;
  taste?: string[];
  temperature?: string;
  channels?: string[];
  properties?: string[];
  tcm_cautions?: string;
  resolved: boolean;
};

// Use enriched dataset if generated by ingestion script (placeholder commits with empty array).
const enrichedHerbs: EnrichedHerbEntry[] =
  (herbLibraryEnrichedData as { herbs?: EnrichedHerbEntry[] }).herbs ?? [];

// Formula dataset — prefer expanded set if generated, else fall back to base 30
type FormulaEntry = { id: string; pinyin: string; english: string; herb_ids: string[] };
const expandedFormulaList = (formulaDataExpanded as { formulas: FormulaEntry[] }).formulas;
const allFormulaData: FormulaEntry[] =
  expandedFormulaList.length > 0
    ? expandedFormulaList
    : (formulaData as { formulas: FormulaEntry[] }).formulas;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const SEVERITY_RANK: Record<SeverityLevel, number> = {
  contraindicated: 2,
  precaution: 1,
  none: 0,
};

const DISCLAIMER =
  "This tool is for educational and professional reference only. " +
  "It does not replace clinical judgment or consultation with a pharmacist. " +
  "Interaction severity may vary based on dosage and herb-to-drug ratio. " +
  "Standard clinical dosages are assumed.";

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Resolves a formula ID to its constituent herb IDs.
 * Returns null if the formula is not found.
 */
function resolveFormula(
  formulaId: string
): { formula: FormulaIdentity; herbIds: string[] } | null {
  const formula = allFormulaData.find((f) => f.id === formulaId);
  if (!formula) return null;
  return {
    formula: {
      id: formula.id,
      pinyin: formula.pinyin,
      english: formula.english,
      source: "nccaom",
      trustTier: "gold",
      resolutionRate: 1.0,
      herb_ids: formula.herb_ids,
    },
    herbIds: formula.herb_ids,
  };
}

// lookupInteraction is now delegated to clinicalDataService (see import above).
// The service handles mock vs. live dispatch and caching transparently.

/**
 * Looks up full herb identity from Gold library first, Silver enriched fallback.
 * For "unresolved-{id}" herb IDs, returns a minimal HerbIdentity with trustTier: "unresolved".
 */
function lookupHerbById(herbId: string): HerbIdentity | null {
  // Unresolved herbs — id gap, cannot look up
  if (herbId.startsWith("unresolved-")) {
    return {
      id: herbId,
      pinyin: "Unknown Herb",
      latin: "",
      english: "Unresolved Herb",
      nccaom_code: null,
      trustTier: "unresolved",
      source: "unresolved",
      resolved: false,
    };
  }

  // Gold library
  const goldEntry = herbLibraryData.herbs.find((h) => h.id === herbId);
  if (goldEntry) {
    type GoldWithEnergetics = typeof goldEntry & {
      active_constituent?: string;
      taste?: string[];
      temperature?: string;
      channels?: string[];
      properties?: string[];
      tcm_cautions?: string;
    };
    const e = goldEntry as GoldWithEnergetics;
    return {
      id: e.id,
      pinyin: e.pinyin,
      latin: e.latin,
      english: e.english,
      nccaom_code: e.nccaom_code,
      trustTier: "gold",
      source: "nccaom_verified",
      resolved: true,
      active_constituent: e.active_constituent,
      taste: e.taste,
      temperature: e.temperature,
      channels: e.channels,
      properties: e.properties,
      tcm_cautions: e.tcm_cautions,
    };
  }

  // Silver enriched fallback
  const silverEntry = enrichedHerbs.find((h) => h.id === herbId);
  if (silverEntry) {
    return {
      id: silverEntry.id,
      pinyin: silverEntry.pinyin,
      latin: silverEntry.latin,
      english: silverEntry.english,
      nccaom_code: silverEntry.nccaom_code,
      trustTier: "silver",
      source: "tcmbank_research",
      tcmbank_id: silverEntry.tcmbank_id,
      resolved: silverEntry.resolved,
      active_constituent: silverEntry.active_constituent,
      taste: silverEntry.taste,
      temperature: silverEntry.temperature,
      channels: silverEntry.channels,
      properties: silverEntry.properties,
      tcm_cautions: silverEntry.tcm_cautions,
    };
  }

  return null;
}

function escalateSeverity(a: SeverityLevel, b: SeverityLevel): SeverityLevel {
  return SEVERITY_RANK[a] >= SEVERITY_RANK[b] ? a : b;
}

function severityToColor(severity: SeverityLevel): "red" | "yellow" | "green" {
  switch (severity) {
    case "contraindicated": return "red";
    case "precaution":      return "yellow";
    case "none":            return "green";
  }
}

// ---------------------------------------------------------------------------
// Main engine function
// ---------------------------------------------------------------------------

/**
 * Runs a full herb-drug interaction check.
 *
 * @param westernMeds - Array of western medications
 * @param tcmInput    - Single herb or TCM formula
 * @param options     - excludedHerbIds: array of herb IDs to exclude from check
 */
export async function checkInteractions(
  westernMeds: WesternMed[],
  tcmInput: TCMInput,
  options: CheckInteractionsOptions = {}
): Promise<InteractionEngineResult> {
  const matches: InteractionMatch[] = [];
  const checkedWithNoInteraction: string[] = [];
  let formulaBreakdown: InteractionEngineResult["formulaBreakdown"] | undefined;
  let lastFreshness: DataFreshness | undefined;

  const excludedSet = new Set(options.excludedHerbIds ?? []);

  // ── Step 1: Resolve herb IDs to check ─────────────────────────────────────
  let herbIdsToCheck: string[];
  let allFormulaHerbIds: string[] = [];
  let resolvedFormula: FormulaIdentity | undefined;

  if (tcmInput.type === "herb") {
    herbIdsToCheck = [tcmInput.herbId];
  } else {
    const resolved = resolveFormula(tcmInput.formulaId);
    if (!resolved) {
      return {
        worstSeverity: "none",
        worstSeverityColor: "green",
        matches: [],
        unresolvedHerbs: [],
        hasUnresolvedHerbs: false,
        checkedWithNoInteraction: [],
        checkedAt: new Date().toISOString(),
        disclaimer: DISCLAIMER,
        dataStatus: FEATURE_FLAGS.useMockData ? "mock_unverified" : "verified",
      };
    }
    resolvedFormula = resolved.formula;
    allFormulaHerbIds = resolved.herbIds;
    herbIdsToCheck = allFormulaHerbIds.filter((id) => !excludedSet.has(id));
  }

  // ── Step 2: Cross-reference each herb against each western med ─────────────
  const herbInteractionMap: Map<string, InteractionMatch[]> = new Map();

  for (const herbId of herbIdsToCheck) {
    // Unresolved herbs have no interaction data — skip lookup
    if (herbId.startsWith("unresolved-")) {
      herbInteractionMap.set(herbId, []);
      continue;
    }

    const libraryHerb = lookupHerbById(herbId);
    if (!libraryHerb) {
      herbInteractionMap.set(herbId, []);
      checkedWithNoInteraction.push(herbId);
      continue;
    }

    const herbMatches: InteractionMatch[] = [];

    for (const med of westernMeds) {
      const { matches: pairMatches, freshness } =
        await lookupInteractionFromService(libraryHerb, med);
      lastFreshness = freshness;

      for (const match of pairMatches) {
        const enriched: InteractionMatch = {
          ...match,
          fromFormula: tcmInput.type === "formula",
          sourceFormula: resolvedFormula,
        };
        herbMatches.push(enriched);
        matches.push(enriched);
      }
    }

    if (herbMatches.length === 0) {
      checkedWithNoInteraction.push(herbId);
    }

    herbInteractionMap.set(herbId, herbMatches);
  }

  // ── Step 3: Sort matches — worst severity first, then by evidence level ───
  const evidenceRank: Record<EvidenceLevel, number> = { high: 2, medium: 1, low: 0 };
  matches.sort((a, b) => {
    const severityDiff = SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity];
    if (severityDiff !== 0) return severityDiff;
    return evidenceRank[b.evidenceLevel] - evidenceRank[a.evidenceLevel];
  });

  // ── Step 4: Determine worst overall severity ───────────────────────────────
  const worstSeverity = matches.reduce<SeverityLevel>(
    (worst, m) => escalateSeverity(worst, m.severity),
    "none"
  );

  // ── Step 5: Build formula breakdown ───────────────────────────────────────
  const unresolvedHerbs: FormulaHerbDetail[] = [];

  if (tcmInput.type === "formula" && resolvedFormula) {
    const herbs: FormulaHerbDetail[] = allFormulaHerbIds.map((herbId) => {
      const isExcluded = excludedSet.has(herbId);
      const isUnresolved = herbId.startsWith("unresolved-");
      const libraryHerb = lookupHerbById(herbId);

      if (isUnresolved) {
        const detail: FormulaHerbDetail = {
          herbId,
          pinyin: libraryHerb?.tcmbank_name ?? herbId.replace("unresolved-", ""),
          latin: "",
          english: "Unresolved Herb",
          nccaom_code: null,
          trustTier: "unresolved",
          resolved: false,
          excluded: isExcluded,
          hasInteraction: false,
          interactions: [],
        };
        return detail;
      }

      if (isExcluded) {
        return {
          herbId,
          pinyin:      libraryHerb?.pinyin      ?? herbId,
          latin:       libraryHerb?.latin       ?? "",
          english:     libraryHerb?.english     ?? "",
          nccaom_code: libraryHerb?.nccaom_code ?? null,
          trustTier:   (libraryHerb?.trustTier  ?? "unresolved") as FormulaHerbDetail["trustTier"],
          resolved:    libraryHerb?.resolved    ?? false,
          excluded: true,
          hasInteraction: false,
          interactions: [],
          taste:       libraryHerb?.taste,
          temperature: libraryHerb?.temperature,
          channels:    libraryHerb?.channels,
          properties:  libraryHerb?.properties,
          tcm_cautions: libraryHerb?.tcm_cautions,
        };
      }

      const herbMatches = herbInteractionMap.get(herbId) ?? [];

      return {
        herbId,
        pinyin:      libraryHerb?.pinyin      ?? herbId,
        latin:       libraryHerb?.latin       ?? "",
        english:     libraryHerb?.english     ?? "",
        nccaom_code: libraryHerb?.nccaom_code ?? null,
        trustTier:   (libraryHerb?.trustTier  ?? "unresolved") as FormulaHerbDetail["trustTier"],
        resolved:    libraryHerb?.resolved    ?? false,
        excluded: false,
        hasInteraction: herbMatches.length > 0,
        interactions: herbMatches,
        taste:       libraryHerb?.taste,
        temperature: libraryHerb?.temperature,
        channels:    libraryHerb?.channels,
        properties:  libraryHerb?.properties,
        tcm_cautions: libraryHerb?.tcm_cautions,
      };
    });

    // Collect unresolved herbs for top-level result field
    for (const h of herbs) {
      if (h.trustTier === "unresolved" && !h.excluded) {
        unresolvedHerbs.push(h);
      }
    }

    const flaggedHerbCount = herbs.filter((h) => h.hasInteraction && !h.excluded).length;
    const unresolvedCount = herbs.filter((h) => h.trustTier === "unresolved").length;

    formulaBreakdown = {
      formula: resolvedFormula,
      herbs,
      flaggedHerbCount,
      totalHerbCount: herbs.length,
      unresolvedCount,
    };
  }

  return {
    worstSeverity,
    worstSeverityColor: severityToColor(worstSeverity),
    matches,
    unresolvedHerbs,
    hasUnresolvedHerbs: unresolvedHerbs.length > 0,
    formulaBreakdown,
    checkedWithNoInteraction,
    checkedAt: new Date().toISOString(),
    disclaimer: DISCLAIMER,
    dataStatus: FEATURE_FLAGS.useMockData ? "mock_unverified" : "verified",
    dataFreshness: lastFreshness,
  };
}
