import { NextRequest, NextResponse } from "next/server";
import Fuse from "fuse.js";
import herbLibrary from "@/data/herbLibrary.json";
import formulaMap from "@/data/formulaMap.json";
import herbLibraryEnriched from "@/data/herbLibraryEnriched.json";
import formulaMapEnriched from "@/data/formulaMapEnriched.json";
import type { TCMSearchResultItem, TCMSearchResponse } from "@/lib/types/clinical";

// ---------------------------------------------------------------------------
// Environment configuration
// ---------------------------------------------------------------------------

const SEARCH_THRESHOLD = parseFloat(
  process.env.SEARCH_THRESHOLD ?? "0.25"
);

const DISCLAIMER =
  "This tool is for educational and professional reference only. " +
  "It does not replace clinical judgment or consultation with a pharmacist. " +
  "Interaction severity may vary based on dosage and herb-to-drug ratio. " +
  "Standard clinical dosages are assumed.";

// ---------------------------------------------------------------------------
// Dataset loading
// Load at module level — Next.js caches between requests.
// Enriched datasets are optional; generated by scripts/ingestTcmBank.ts.
// ---------------------------------------------------------------------------

type EnrichedHerbEntry = {
  id: string;
  pinyin: string;
  latin: string;
  english: string;
  nccaom_code: string | null;
  trustTier: "silver";
  source: "tcmbank_research";
  tcmbank_id?: string;
  active_constituent?: string;
};

type EnrichedFormulaEntry = {
  id: string;
  pinyin: string;
  english: string;
  trustTier: "silver";
  source: "tcmbank_research";
  resolutionRate: number;
  herb_ids: string[];
};

// Use enriched datasets if generated by ingestion script, otherwise empty arrays.
// The placeholder files (data/herbLibraryEnriched.json, data/formulaMapEnriched.json)
// are committed with empty arrays until npx ts-node scripts/ingestTcmBank.ts is run.
const enrichedHerbs: EnrichedHerbEntry[] =
  (herbLibraryEnriched as { herbs?: EnrichedHerbEntry[] }).herbs ?? [];

const enrichedFormulas: EnrichedFormulaEntry[] =
  (formulaMapEnriched as { formulas?: EnrichedFormulaEntry[] }).formulas ?? [];

// ---------------------------------------------------------------------------
// Fuse.js indexes
// ---------------------------------------------------------------------------

type GoldHerbEntry = (typeof herbLibrary.herbs)[number];
type GoldFormulaEntry = (typeof formulaMap.formulas)[number];

const goldHerbFuse = new Fuse(herbLibrary.herbs as GoldHerbEntry[], {
  threshold: SEARCH_THRESHOLD,
  minMatchCharLength: 2,
  includeScore: true,
  shouldSort: true,
  keys: [
    { name: "pinyin",      weight: 0.4 },
    { name: "english",     weight: 0.3 },
    { name: "latin",       weight: 0.2 },
    { name: "nccaom_code", weight: 0.1 },
  ],
});

const goldFormulaFuse = new Fuse(formulaMap.formulas as GoldFormulaEntry[], {
  threshold: SEARCH_THRESHOLD,
  minMatchCharLength: 2,
  includeScore: true,
  shouldSort: true,
  keys: [
    { name: "pinyin",  weight: 0.6 },
    { name: "english", weight: 0.4 },
  ],
});

const silverHerbFuse = new Fuse(enrichedHerbs, {
  threshold: SEARCH_THRESHOLD,
  minMatchCharLength: 2,
  includeScore: true,
  shouldSort: true,
  keys: [
    { name: "pinyin",  weight: 0.5 },
    { name: "english", weight: 0.3 },
    { name: "latin",   weight: 0.2 },
  ],
});

const silverFormulaFuse = new Fuse(enrichedFormulas, {
  threshold: SEARCH_THRESHOLD,
  minMatchCharLength: 2,
  includeScore: true,
  shouldSort: true,
  keys: [
    { name: "pinyin",  weight: 0.6 },
    { name: "english", weight: 0.4 },
  ],
});

// ---------------------------------------------------------------------------
// Result mapping helpers
// ---------------------------------------------------------------------------

function goldHerbToItem(
  herb: GoldHerbEntry,
  score: number
): TCMSearchResultItem {
  type WithEnergetics = GoldHerbEntry & { active_constituent?: string };
  const h = herb as WithEnergetics;
  return {
    type: "herb",
    id: h.id,
    pinyin: h.pinyin,
    english: h.english,
    latin: h.latin,
    nccaom_code: h.nccaom_code,
    trustTier: "gold",
    source: "nccaom_verified",
    score,
    active_constituent: h.active_constituent,
  };
}

function goldFormulaToItem(
  formula: GoldFormulaEntry,
  score: number
): TCMSearchResultItem {
  return {
    type: "formula",
    id: formula.id,
    pinyin: formula.pinyin,
    english: formula.english,
    nccaom_code: null,
    trustTier: "gold",
    source: "nccaom",
    score,
    herb_count: formula.herb_ids.length,
    resolution_rate: 1.0,
  };
}

function silverHerbToItem(
  herb: EnrichedHerbEntry,
  score: number
): TCMSearchResultItem {
  return {
    type: "herb",
    id: herb.id,
    pinyin: herb.pinyin,
    english: herb.english,
    latin: herb.latin,
    nccaom_code: herb.nccaom_code,
    trustTier: "silver",
    source: "tcmbank_research",
    score,
    active_constituent: herb.active_constituent,
  };
}

function silverFormulaToItem(
  formula: EnrichedFormulaEntry,
  score: number
): TCMSearchResultItem {
  return {
    type: "formula",
    id: formula.id,
    pinyin: formula.pinyin,
    english: formula.english,
    nccaom_code: null,
    trustTier: "silver",
    source: "tcmbank_research",
    score,
    herb_count: formula.herb_ids.length,
    resolution_rate: formula.resolutionRate,
  };
}

// ---------------------------------------------------------------------------
// Clinical safety filter — prevents pinyin near-homophone confusion
//
// Problem: Fuse.js edit-distance scoring treats "dan shen" / "dang shen" /
// "ren shen" as near-matches because they differ by 1–2 characters.
// In TCM practice these are completely different herbs; a mix-up is a
// clinical error.
//
// Fix: for multi-word queries, each word (except the last) must EXACTLY match
// the corresponding word in the result's pinyin, english, or latin field.
// The final word allows prefix matching so in-progress typing still works.
// A single-word query bypasses the filter — Fuse.js fuzzy is appropriate there.
//
// Examples:
//   "dang shen" → "Dan Shen" pinyin[0] "dan" ≠ "dang" → excluded
//   "dan shen"  → "Dang Shen" pinyin[0] "dang" ≠ "dan" → excluded
//   "ren shen"  → "Dan Shen" pinyin[0] "dan" ≠ "ren" → excluded
//   "dan sh"    → "Dan Shen" pinyin[0] "dan"="dan" ✓, pinyin[1] "shen".startsWith("sh") ✓ → included
//   "red sage root" → "Dan Shen" english "Red Sage Root" → "red"="red" ✓, "sage"="sage" ✓, "root".startsWith("root") ✓ → included
// ---------------------------------------------------------------------------

function clinicalSafetyFilter(query: string, item: TCMSearchResultItem): boolean {
  const queryWords = query.trim().toLowerCase().split(/\s+/);
  if (queryWords.length < 2) return true; // single word — Fuse.js sufficient

  function wordSequenceMatches(fieldValue: string): boolean {
    const fieldWords = fieldValue.toLowerCase().split(/\s+/);
    for (let i = 0; i < queryWords.length; i++) {
      if (i >= fieldWords.length) return false;
      const isLastQueryWord = i === queryWords.length - 1;
      if (isLastQueryWord) {
        // Last word: allow prefix match (user may still be typing)
        if (!fieldWords[i].startsWith(queryWords[i])) return false;
      } else {
        // Non-last words: require exact match — no fuzzy across syllable boundaries
        if (fieldWords[i] !== queryWords[i]) return false;
      }
    }
    return true;
  }

  return (
    wordSequenceMatches(item.pinyin) ||
    wordSequenceMatches(item.english) ||
    (item.latin ? wordSequenceMatches(item.latin) : false)
  );
}

// ---------------------------------------------------------------------------
// GET /api/search/tcm?q={query}&type=herb|formula|all
// ---------------------------------------------------------------------------

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const q = searchParams.get("q")?.trim() ?? "";
  const typeParam = searchParams.get("type") ?? "all";

  if (q.length < 2) {
    return NextResponse.json(
      { error: "Parameter q must be at least 2 characters" },
      { status: 400 }
    );
  }

  const searchHerbs = typeParam === "all" || typeParam === "herb";
  const searchFormulas = typeParam === "all" || typeParam === "formula";

  // ── Search Gold tier ──────────────────────────────────────────────────────
  const goldItems: TCMSearchResultItem[] = [];

  if (searchHerbs) {
    goldHerbFuse.search(q).forEach((r) => {
      const item = goldHerbToItem(r.item as GoldHerbEntry, r.score ?? 1);
      if (clinicalSafetyFilter(q, item)) goldItems.push(item);
    });
  }

  if (searchFormulas) {
    goldFormulaFuse.search(q).forEach((r) => {
      const item = goldFormulaToItem(r.item as GoldFormulaEntry, r.score ?? 1);
      if (clinicalSafetyFilter(q, item)) goldItems.push(item);
    });
  }

  // Sort Gold results by score (lower = better)
  goldItems.sort((a, b) => a.score - b.score);

  // ── Cascade: return Gold if found, else search Silver ─────────────────────
  if (goldItems.length > 0) {
    const results = goldItems.slice(0, 8);
    const response: TCMSearchResponse = {
      api_version: "3.0",
      results,
      searchedFallback: false,
      query: q,
      total: results.length,
      disclaimer: DISCLAIMER,
    };
    return NextResponse.json(response);
  }

  // ── Silver tier fallback ──────────────────────────────────────────────────
  const silverItems: TCMSearchResultItem[] = [];

  if (searchHerbs) {
    silverHerbFuse.search(q).forEach((r) => {
      const item = silverHerbToItem(r.item as EnrichedHerbEntry, r.score ?? 1);
      if (clinicalSafetyFilter(q, item)) silverItems.push(item);
    });
  }

  if (searchFormulas) {
    silverFormulaFuse.search(q).forEach((r) => {
      const item = silverFormulaToItem(r.item as EnrichedFormulaEntry, r.score ?? 1);
      if (clinicalSafetyFilter(q, item)) silverItems.push(item);
    });
  }

  silverItems.sort((a, b) => a.score - b.score);
  const silverResults = silverItems.slice(0, 8);

  const response: TCMSearchResponse = {
    api_version: "3.0",
    results: silverResults,
    searchedFallback: silverResults.length > 0,
    query: q,
    total: silverResults.length,
    disclaimer: DISCLAIMER,
  };

  return NextResponse.json(response);
}
